### ISSUE TITLE
Lounge Wifi in Mannheim does not work

### ISSUE THREAD

**Issue by madonius** [sistason/db_wlan_manager#8]
Trying to log in in the Lounge in Mannheim, I get:
```html
<html>
<head>
<title>Forbidden access</title>
</head>
<body style="text-align:center">
<div style="width:80%; border:1px solid #64696C; color:#64696C; font-weight:bold; text-align:center; padding:20px; margin:auto; margin-top:20px">
<p id="small_p" style="font-size:small;">Forbidden access</p>
<p id="large_p" style="font-size:large;">Your current web browser cannot access this page.</p>
</div>
</body>
</html>
```

**Comment by sistason** [comment]
where do you get this? As output from the script?
Are you able to check the DBLounges somewhere again/else, to see if this was a API-Change or a Bug?

**Comment by madonius** [comment]
Yes this is the output returned from the script when I run `./manager.py`
I will try to login to some other lounge's wifi and report.
The issue could be replicated today.

**Comment by madonius** [comment]
Since everything changed about the wifi, I will close the issue ^^

**Comment by sistason** [comment]
oh well, I'm not looking forward to my next train ride then... -.-
thanks for the headsup ;)
